### ISSUE TITLE
error bubbles don't go away

### ISSUE THREAD

**Issue by pcause** [polyipseity/obsidian-terminal#13]
I was trying to set up terminal to invoke wsl2.  took a while (will post what the setup needs to be in separate issue) but as I do I get error bubbles.  I close the bad terminal and try again and the error bubble keep growing and don't go away.  only last/bottom one does.

**Comment by polyipseity** [comment]
What were your notice timeout settings (`Notice timeout (s)`, `Error notice timeout (s)`)? The error bubbles (they are called notices) do not go away if the above settings are exactly 0.

Also, it would be very helpful if you could can screen record what you exactly mean.

**Comment by polyipseity** [comment]
Forgot to mention: Please also update the plugin to the latest version
(v3.3.0) first.

**Comment by polyipseity** [comment]
@pcause, I hope you are well. Could you reconfirm so that I could close or resolve the problem?

**Comment by pcause** [comment]
yes, cloded
