### ISSUE TITLE
add a wsl2 terminal setup for windows

### ISSUE THREAD

**Issue by pcause** [polyipseity/obsidian-terminal#14]
perhaps createn a default wsl setup profile for Windows.  I set up wsl2 accesson Win11.  

It is integrated, xxecutable is "dows\System32\bash.exe", use conhost.  python can be left blank or path is:

C:\Users\username\AppData\Local\Programs\Python\Python311\python.exeq

where you have to change username to your user name.  You might be able to get user name from within obsidian but not sure.  This location of python works for me but might be different depending on how installed.  if you don't have python it launches but the default window size/display can be a bit messed up if you use tmux.

Even if you don't include, perhaps give this as a starter for other users in the README or the nite you popup on first install.

**Comment by polyipseity** [comment]
- Added to documentation in 7a787996ddf96403ee29dfb13c0f9a9961853474.
- Added preset in 720388c0fdf0833137df479e43f24524939252c2.
