### ISSUE TITLE
Possibile to use Git Bash on Windows?

### ISSUE THREAD

**Issue by epac-tom** [polyipseity/obsidian-terminal#15]
Is it possible to use Git Bash on Windows?

**Comment by polyipseity** [comment]
Set `(Git installation)\bin\bash.exe` (e.g. `C:\Program Files\Git\bin\bash.exe`) as the executable.

**Comment by polyipseity** [comment]
Released in [3.4.0](https://github.com/polyipseity/obsidian-terminal/releases/tag/3.4.0).
