### ISSUE TITLE
[Feature request] New Windows terminal integration

### ISSUE THREAD

**Issue by keerah** [polyipseity/obsidian-terminal#16]
New Windows terminal integration if it's possible one day, please

**Comment by polyipseity** [comment]
If it is the former, create a profile of type "External" and set "wt" as
the executable.

**Comment by keerah** [comment]
I wouldn't need this plugin to run wt externally, there're simpler plugins for this.
And I suppose wt integration into the Obsidian's interface is quite difficult, so it's just an idea

**Comment by polyipseity** [comment]
I think it would help to think about what it even means to integrate WT
directly.

If you are talking about integrating the full application, that would
require embedding the native window into a webpage (Electron). There does
not seem to be a way to call native code from Obsidian (without some ugly
plugin installation process).

An alternative would be to copy the desired features from WT and implement
it in the plugin, which is much more feasible.

(Maybe I could make a setting to grab the profiles from WT and import
them...)

**Comment by keerah** [comment]
Yeah, I understand. But it still won't support some cool wt features like drag-n-drop features and themes, right? 
Thanks for listening anyway

**Comment by polyipseity** [comment]
Theming is very much possible but that would require quite some time to add
settings for it properly. (Or I could expose it very uglily in the
settings.)

By drag-n-drop, you mean pasting the filename automatically when a file is
dragged onto the terminal? This is also possible and should not take too
long to implement.

**Comment by polyipseity** [comment]
Themeing is now supported in the latest version (v3.8.0). It is not so user-friendly right now, however:
1. Open the profile editing modal.
2. Click on the `Edit` button labeled `Data`. It should open up a new modal in which there is a large textbox.
3. You should see `terminalOptions` inside the text area labeled `Data`.
4. Refer to the [`xterm.js` documentation](https://github.com/xtermjs/xterm.js/blob/2fdb46919ce7a329afe65fe69bcf948d310a2b8a/typings/xterm.d.ts#L26) to set the options.
5. Then save the profile and start a new terminal with the new profile.

You can see an example of setting the font in #11.

**Comment by polyipseity** [comment]
> > Themeing is now supported in the latest version (v3.8.0). It is not so user-friendly right now, however:
> > 
> > 1. Open the profile editing modal.
> > 2. Click on the `Edit` button labeled `Data`. It should open up a new modal in which there is a large textbox.
> > 3. You should see `terminalOptions` inside the text area labeled `Data`.
> > 4. Refer to the [`xterm.js` documentation](https://github.com/xtermjs/xterm.js/blob/2fdb46919ce7a329afe65fe69bcf948d310a2b8a/typings/xterm.d.ts#L26) to set the options.
> > 5. Then save the profile and start a new terminal with the new profile.
> > 
> > You can see an example of setting the font in #11.
> 
> Tried using docs for background but always returned 'malformed data'...?

Example:

```JSON
{
	"documentOverride": null,
	"theme": {
		"background": "#123456"
	}
}
```
