### ISSUE TITLE
empty tasks

### ISSUE THREAD

**Issue by pcause** [polyipseity/obsidian-terminal#17]
I have notes "tasks" that look like:

- [  ]

this happens when I enter a tasks and at the end of the line hit enter.  that - [ ] is automatically added, i think by the tasks plugin.  Can you add an option to ignore "empty todos, which are todos with the checkbox but no content.

**Comment by polyipseity** [comment]
🤔 Did you mean to open this issue in https://github.com/obsidian-tasks-group/obsidian-tasks or https://github.com/Leonezz/obsidian-tasks-calendar-wrapper?

**Comment by pcause** [comment]
I think that in general the plugin should ignore empty tasks, so independent of what tasks or others do these empty tasks should be ignored.

**Comment by polyipseity** [comment]
Seems like you have finally filed the issue correctly at https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/issues/8.
