### ISSUE TITLE
Malformed data message

### ISSUE THREAD

**Issue by legolasdimir** [polyipseity/obsidian-terminal#19]
When I check for plugin updates and I see there's an update for terminal that then runs, After the update I get a message that says malformed data. I have no idea what's causing this or how to fix it.

**Comment by polyipseity** [comment]
It is normal to get this message when you update the plugin since the `data.json` format has changed slightly. All of your old settings should be intact. I should indicate this in the notice to avoid future confusion.

**Comment by polyipseity** [comment]
Ok, I have removed the "Malformed data" notice entirely instead to avoid confusion in 4d8a0fa459c5d982160bdfedc5e09ac9f9dd19f3. Since the plugin fixes broken data, it is usually not something for users to worry about. The message is still accessible in the developer console.
