### ISSUE TITLE
[Feature Request] Ability to customize font? 

### ISSUE THREAD

**Issue by ereduled** [polyipseity/obsidian-terminal#20]
I would like to start by thanking you for creating such a useful plugin. As someone who spends a lot of time using terminals, this plugin has been a game changer for me. It allows me to use the knowledge aspect of it along with the working aspect, allows me to do most of my work within Obsidian itself.

However, I have noticed that there is no option to customize the font. Therefore, I am writing this feature request to ask if it would be possible to add this functionality.

It would be great if users could choose their preferred font type and size within the plugin settings. This customization will not only enhance user experience but also make reading and typing more comfortable for those who spend long hours working on terminals.

![image](https://github.com/polyipseity/obsidian-terminal/assets/25099244/00942b21-6e8f-4a40-a5c2-d7a1c838acea)

**Comment by polyipseity** [comment]
Shipped with v3.10.0 (a64e5b1c5c9153581d2db35acb6c5460bd9655c5).

**Comment by ereduled** [comment]
Thanks!
