### ISSUE TITLE
proxychains4 zsh: command not found: proxychains4

### ISSUE THREAD

**Issue by xucongyong** [polyipseity/obsidian-terminal#21]
> proxychains4
zsh: command not found: proxychains4

**Comment by polyipseity** [comment]
Did you install Obsidian using Snap or Flatpak?

**Comment by polyipseity** [comment]
@xucongyong Potential fixes:
- If you are using Snap to install Obsidian, you need make `proxychains4` accessible through one of the following paths listed here: https://github.com/snapcore/snapd/blob/bd642de304dc32b95ca45fe640ae8d23b09b44fc/cmd/snap-confine/mount-support.c#L953-L981.
- If you are using Flatpak to install Obsidian, run the following (replace `ApplicationID`, you can find Obsidian's ID using `sudo flatpak list`):
```console
sudo flatpak override ApplicationID --filesystem=host
```
- If the above are too troublesome or do not work, the alternative would be to not use Snap or Flatpak to install Obsidian. That would require uninstalling Obsidian first, and then installing Obsidian using AppImage only.
