### ISSUE TITLE
How to add fish shell into the terminal plugin 

### ISSUE THREAD

**Issue by abdelkareemkobo** [polyipseity/obsidian-terminal#23]
I am using pop os and trying to use default bash or fish or anything but only get the /bin/sh which don't contain any commands from my .bashrc or fish shell how to make my bashrc is the defualt or fish

**Comment by polyipseity** [comment]
Go to settings and press the edit button on "Profiles". Then edit the entry
labelled "linuxIntegratedDefault". Now you should see a text box labelled
"Executable" with the value "/bin/sh". Change that to "bash" or "fish".
Exit settings and you should be able open an integrated terminal using
"bash" and "fish''.

**Comment by abdelkareemkobo** [comment]
this is the output when i use fish 
![image](https://github.com/polyipseity/obsidian-terminal/assets/72500236/6447113c-cda5-4f75-adf1-90601d5e08a7)

**Comment by polyipseity** [comment]
If you have installed Obsidian using Flatpak, you need to add file
permissions to access those executables. Run the following in a terminal to
add permissions (replace `ApplicationID`, you can find Obsidian's ID using
`sudo flatpak list`):
```console
sudo flatpak override ApplicationID --filesystem=host
```

**Comment by abdelkareemkobo** [comment]
![image](https://github.com/polyipseity/obsidian-terminal/assets/72500236/df5c5940-ad31-4ced-b988-a70e70b0fe6b)
yes, i have installed it with flatpak but it dones'nt work!
![image](https://github.com/polyipseity/obsidian-terminal/assets/72500236/214248e9-fe0b-4934-b0b1-4e30561e844d)

**Comment by polyipseity** [comment]
Hmm... might need to restart Obsidian as well. (Also, why's there "No
module named 'nvidia'"? The plugin should not be importing it...)

**Comment by abdelkareemkobo** [comment]
I restarted obsidain, I don't know why this error of nvidia shows, but the bash and fish or working nice with xterm,accelerate and any terminal i have in my own labtop

**Comment by abdelkareemkobo** [comment]
oh, sorry  i forget to told you that you have made a really nice work for this project!keep going :smile:

**Comment by polyipseity** [comment]
I think we can isolate this problem to see whether it is caused by the
flatpak sandbox by reinstalling Obsidian using the AppImage instead of
Flatpak from the official website and see whether it works.

**Comment by polyipseity** [comment]
@abdelkareemkobo: Hmm... Did anything interesting happen? Or are you no longer interested in this issue?
