### ISSUE TITLE
Can't open integrated terminal (Linux Mint) and help with a "script"?

### ISSUE THREAD

**Issue by ReaderGuy42** [polyipseity/obsidian-terminal#24]
I'm trying to automate my conversion from .md to .pdf via LaTeX. I'm using `latexmk -pdf` to turn a converted .tex file to a PDF.

Can your plugin automate this?

Also, I can't seem to open the integrated terminal. It worked once when I first installed the plugin and now even after removal (including the folder) and reinstalling (and restarting Obsidian) it won't open anymore.

Any help?
Thanks!

**Comment by polyipseity** [comment]
For the first question, the plugin is meant for interacting with a
terminal, not for just simply running commands. Instead, you can use the
Shell Commands plugin (https://github.com/Taitava/obsidian-shellcommands)
to automate it. Looks like you can use their events to run the command when
a file changes:
https://publish.obsidian.md/shellcommands/Events/File+content+modified

For the second question, can you open the developer console
(`Ctrl`+`Shift`+`I`, `Cmd`+`Opt`+`I` on macOS) and post any messages that
you have seen? Also, describe how the terminal "doesn't open anymore".

**Comment by ReaderGuy42** [comment]
I'm on Linux and the terminal selector shows that most of the ones available by default are incompatible.

I was able to solve it with Shell Commands, thanks! Also, the integrated terminal opened again, don't know what was wrong last time. Thanks anyways!
