### ISSUE TITLE
Terminal pops up, even if I chose integrated Terminal

### ISSUE THREAD

**Issue by herbertnikolajewskidci** [polyipseity/obsidian-terminal#25]
How do I solve this? When I open an integrated Terminal window always pops up a second seperate window. What did I wrong?

**Comment by polyipseity** [comment]
Can you clarify what the separate window is?
- If you are on Windows and the separate window is a console window that
appears and disappears momentarily, this is expected.
- If the separate window is a new Obsidian window, then you need to ensure
"New instance behavior" is not set to "New window".
- Otherwise, can you send a screenshot/video of what went wrong, your OS
platform, and your plugin settings (`data.json`)?

**Comment by ninzhan** [comment]
Same issue here on Windows, terminal opens a new window which sticks around. Can be operated in both the obsidian window and the actual terminal. Settings are as follows:

{
	"addToCommand": true,
	"addToContextMenu": true,
	"createInstanceNearExistingOnes": true,
	"errorNoticeTimeout": 0,
	"exposeInternalModules": true,
	"focusOnNewInstance": true,
	"hideStatusBar": "focused",
	"language": "",
	"lastReadChangelogVersion": "3.12.2",
	"newInstanceBehavior": "newHorizontalSplit",
	"noticeTimeout": 5,
	"openChangelogOnUpdate": true,
	"pinNewInstance": false,
	"preferredRenderer": "webgl",
	"profiles": {
		"09f28abb-2542-46b2-9513-7a9a05cbf10b": {
			"args": [],
			"executable": "powershell",
			"name": "",
			"platforms": {
				"win32": true
			},
			"pythonExecutable": "python3",
			"restoreHistory": true,
			"successExitCodes": [
				"0",
				"SIGINT",
				"SIGTERM"
			],
			"terminalOptions": {},
			"type": "integrated",
			"useWin32Conhost": true
		}
	},
	"recovery": {}
}

I tested this with powershell, ubuntu wls, and git bash. All 3 of them had similar behaviour. 

In addition, there was an error with "Terminal resizer exited unexpectedly: 1" The code was 1 half the time, and a 4 digit number starting with 9 the other times. Can't remember if it was 9909 or some variant of that.

**Comment by polyipseity** [comment]
@herbertnikolajewskidci, @ninzhan: Okay, it looks like the latest `pywinctl` module has removed `BaseWindow`, causing the resizer to fail. Can you check if it works now after running `pip3 install psutil==5.9.5 pywinctl==0.0.50 typing_extensions==4.7.1` and updating the plugin to the latest version (3.12.3)?

**Comment by ninzhan** [comment]
That works properly now as far as I can tell!
