### ISSUE TITLE
[Bug] Terminal Hangs Obsidian

### ISSUE THREAD

**Issue by iamrecursion** [polyipseity/obsidian-terminal#26]
When opening a terminal on the latest Obsidian insider, `1.4.5`, the entire UI hangs and requires me to force-quit Obsidian.

**Comment by polyipseity** [comment]
Hanging the entire UI is a bit odd... I can really only think of the renderer process crashing.

Is there anything in the developer console? Does changing the "Preferred renderer" to the other two options help?

**Comment by iamrecursion** [comment]
All is fine until the terminal is actually focused, and there is nothing in the developer console as it seems to hang the entire app. The behavior is the same with all of the renderers as best I can tell.

**Comment by mbabiaczykaquiva** [comment]
The same issue is on my side.
MAC OS: Ventura 13.5.1 (22G90)
Obsidian: 1.4.5 installer 1.3.5
Terminal plugin: 3.12.3

**Comment by iamrecursion** [comment]
My system matches the above, actually. I cannot reproduce it on iOS or iPadOS.

**Comment by polyipseity** [comment]
I do not have many ideas about this right now... Testing on macOS 12 does
work. Maybe a video of Obsidian (opened using `Terminal.app` to get more
logs) hanging with the developer console open might yield information that
helps me discover the problem?

**Comment by iamrecursion** [comment]
There was nothing in either the terminal or console. I did some picking things apart, and as best I can tell it is a conflict with [Obsidian Image Toolkit](https://github.com/sissilab/obsidian-image-toolkit). If you install that and terminal (this works in the sandbox vault for me), and try and launch the developer console, it hangs.

**Comment by iamrecursion** [comment]
@mbabiaczykaquiva Do you also have that plugin installed?

**Comment by polyipseity** [comment]
@iamrecursion, @mbabiaczykaquiva: It should be fixed now in 0879e6d0a8a6c1eebef730376bd7df58fdfba4a5. If you download the development version via BRAT or download manually from the [latest release](https://github.com/polyipseity/obsidian-terminal/releases/tag/latest), it should no longer freeze.

**Comment by polyipseity** [comment]
> There was nothing in either the terminal or console. I did some picking things apart, and as best I can tell it is a conflict with [Obsidian Image Toolkit](https://github.com/sissilab/obsidian-image-toolkit). If you install that and terminal (this works in the sandbox vault for me), and try and launch the developer console, it hangs.

@iamrecursion: Forgot to mention that this is exactly what I need to reproduce it. Thanks.

**Comment by mbabiaczykaquiva** [comment]
@polyipseity it is working!!! Thank you! :D

**Comment by iamrecursion** [comment]
I'm so glad that my digging helped! I can confirm that this fixes it for me!

**Comment by polyipseity** [comment]
Apparently this also fixes a bug reported privately:

> If I have e.g. ten paragraphs in a note and I put the caret/cursor in the first, so that I can start editing the first paragraph. If I then scroll down to the bottom of the page so that the caret isn't visible, the page will scroll up to show the caret after one second. Same applies for horizontal direction.
>
> Aha it's terminal. I have it in the right tab at all times. It seems that it is a timer that triggers every 1 second that brings the caret into view.

**Comment by polyipseity** [comment]
Released in [3.13.0](https://github.com/polyipseity/obsidian-terminal/releases/tag/3.13.0).

**Comment by iamrecursion** [comment]
Thanks so much for fixing this! I'm sorry it took me so long to have time to try and get a minimal repro!
