### ISSUE TITLE
Changelog Opening Consistently

### ISSUE THREAD

**Issue by iamrecursion** [polyipseity/obsidian-terminal#27]
The changelog is opening every time I start Obsidian, even if I have "show changelog after update" turned off.

**Comment by polyipseity** [comment]
Probably the same problem as [obsidian-modules#4](https://github.com/polyipseity/obsidian-modules/issues/4).

Try replacing both `maxPending:X9` (3 instances) and `maxPending:1e3` (1 instance) with `maxPending:Infinity` inside `main.js` and see if it fixes the problem. If so, I just need to make a new release because the fix has already been implemented.

**Comment by iamrecursion** [comment]
It still seems to happen for me, but I am not sure I did it right!

**Comment by polyipseity** [comment]
Perhaps it might be a slightly different issue then that also causes saving
`data.json` to fail. Are there stacktraces that you can see if you modify
the settings?

**Comment by iamrecursion** [comment]
No errors, no!

**Comment by polyipseity** [comment]
Is `data.json` failing to save? What does the `data.json` look like?

**Comment by iamrecursion** [comment]
Here is the current contents:

```json
{
  "addToCommand": true,
  "addToContextMenu": true,
  "createInstanceNearExistingOnes": false,
  "errorNoticeTimeout": 0,
  "exposeInternalModules": true,
  "focusOnNewInstance": true,
  "hideStatusBar": "focused",
  "language": "",
  "lastReadChangelogVersion": "3.12.3",
  "newInstanceBehavior": "newTab",
  "noticeTimeout": 5,
  "openChangelogOnUpdate": false,
  "pinNewInstance": false,
  "preferredRenderer": "dom",
  "profiles": {
    "developerConsole": {
      "name": "",
      "restoreHistory": true,
      "successExitCodes": [
        "0",
        "SIGINT",
        "SIGTERM"
      ],
      "terminalOptions": {},
      "type": "developerConsole"
    }
  },
  "recovery": {}
}
```

**Comment by polyipseity** [comment]
It works normally... In this case, `main.js` might be corrupted. Can you send the current `main.js` as an attachment here, then try reinstalling the plugin?

**Comment by iamrecursion** [comment]
Here's the current state of the plugin's folder. It has my attempts at changing things as you mentioned [here](https://github.com/polyipseity/obsidian-terminal/issues/27#issuecomment-1715833773) in `main.js`.

[terminal.zip](https://github.com/polyipseity/obsidian-terminal/files/12641457/terminal.zip)

**Comment by iamrecursion** [comment]
Reinstalling does seem to have fixed that issue. Unfortunately I am still seeing #26 after reinstalling.

**Comment by polyipseity** [comment]
> Reinstalling does seem to have fixed that issue. Unfortunately I am still seeing #26 after reinstalling.

Alright, I will have another go at that issue.
