### ISSUE TITLE
Obsidian shortcuts dont work when focused in integrated Terminal

### ISSUE THREAD

**Issue by sanjarcode** [polyipseity/obsidian-terminal#33]
None of the obsidian hotkeys get registered if focus is in the integrated terminal.
I am using `macOS default Integrated` config for the terminal.

Practically, I am unable to open Command Palette.

Is this intentional? An example: I use vscode, and its Command Palette does open up when triggered from inside the integrated terminal. So I guess the UX decision to let shortcuts be triggered is ok.

---

And thanks for the plugin!

**Comment by polyipseity** [comment]
This is intentional. You can however unfocus the terminal by pressing
Ctrl+Shift+` (backtick) (and refocus again by pressing the same key
combination), then you can use other Obsidian hotkeys.

**Comment by polyipseity** [comment]
Added a sentence in the readme about this in d9f9039e1fd47db1b94b6a2ccf26afd360145a71.
