### ISSUE TITLE
The integrated  terminal is no longer spawning

### ISSUE THREAD

**Issue by khietdoansecond** [polyipseity/obsidian-terminal#34]
This is all of sudden, I am no longer able to open an integrated terminal within the Obisidian. I triggered the command from Command Palette, nothing happened. If I tried with the external one, it worked. 

I have tried every possible profile of zsh/bash/MacOS Integrated. But none of them works.

The Profiles List:
![ảnh](https://github.com/polyipseity/obsidian-terminal/assets/84166550/76d8cd57-613e-4185-a115-d3c7cba7c59c)

Could you help give a guidance to troubleshoot this issue ? Thanks a lot !

**Comment by polyipseity** [comment]
Check if the plugin is updated. Then, can you press `Cmd + Option + J` to open the developer console, then try to open all the profiles, and check if there are any messages in the console.
