### ISSUE TITLE
update readme for using windows terminal as internal terminal for WSL2

### ISSUE THREAD

**Issue by pcause** [polyipseity/obsidian-terminal#4]
For folks using Windows and WSL, you might add to the readme that opening the settings for Windows terminal and using what is entered in the "command Line" setting of a terminal profile you want to launch can be used.  So if you have a fedora profile, it might have a Command Line of:

c:\windows\system32\wsl.exe -d fedora

**Comment by polyipseity** [comment]
Added in 57a85254e1fd7bf9ed5a6feab08784b26d983090.
