### ISSUE TITLE
Can't find "python executable" in Plugin Settings

### ISSUE THREAD

**Issue by Itisalex2** [polyipseity/obsidian-terminal#44]
OS: Mac Sonoma 14.6.1

Hi I am having trouble getting the integrated terminal to work with my Mac. I always get the error:

```
Traceback (most recent call last):
                                    File "<string>", line 2, in <module>
                                                                        ImportError: cannot import name 'waitstatus_to_exitcode' from 'os' (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/os.py)
```

I understand that this means my Python version is wrong. However, when I try to check my Python version via the Python executable in plugin setting, I don't actually see the Python executable option.

Here is what I see in my plugin settings:
<img width="776" alt="Screenshot 2024-12-16 at 2 07 58 PM" src="https://github.com/user-attachments/assets/3343df28-9024-40c0-8c87-a1df9589d66a" />
<img width="782" alt="Screenshot 2024-12-16 at 2 08 11 PM" src="https://github.com/user-attachments/assets/68537334-fd6c-4f08-9cdd-54f145ad7a1f" />

Where can I get access to my Python version and change it? My external terminal works (it uses Python 3.12).

**Comment by Itisalex2** [comment]
Nevermind, i figured out my problem. The "Python executable" is not present in the terminal plugin settings through the obsidian interface. However, it is present in .obsidian/plugings/terminal/data.json. I changed the following line:

```
# Before:
"darwinIntegratedDefault": {
...
"pythonExecutable": "python3"
...
}

# After:
"darwinIntegratedDefault": {
...
"pythonExecutable": "/Library/Frameworks/Python.framework/Versions/3.12/bin/python3"
...
}
```

The pathing was wrong somehow but it works now with the absolute path.

**Comment by polyipseity** [comment]
Just heads  up, it is available in the UI but you need to click into the UI that edits a profile.
