### ISSUE TITLE
main.js missing

### ISSUE THREAD

**Issue by tinoargentino** [polyipseity/obsidian-terminal#5]
where is main.js?

**Comment by polyipseity** [comment]
Oops, I forgot that `main.js` is from the release. I have changed the wording (c87139df1ea3e97089035ff05824a894cc554b3a). You should go to https://github.com/polyipseity/obsidian-terminal/releases and download the 3 files from the latest release instead.

**Comment by tinoargentino** [comment]
thanks!!!
